2023-08-06 17:31:52 [INFO]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8563
2023-08-06 17:31:52 [INFO]: [33mPress CTRL+C to quit[0m
2023-08-06 17:31:59 [INFO]: 127.0.0.1 - - [06/Aug/2023 17:31:59] "GET / HTTP/1.1" 200 -
2023-08-06 17:31:59 [INFO]: 127.0.0.1 - - [06/Aug/2023 17:31:59] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2023-08-06 17:32:11 [ERROR]: Exception on /get_by_id/25 [GET]
Traceback (most recent call last):
  File "C:\Users\Vikas Datir\PycharmProjects\py_restapi\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Vikas Datir\PycharmProjects\py_restapi\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Vikas Datir\PycharmProjects\py_restapi\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Vikas Datir\PycharmProjects\py_restapi\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Vikas Datir\PycharmProjects\py_restapi\rest_api_app.py", line 53, in get_by_id
    cust_obj = Customers(config)
NameError: name 'config' is not defined
2023-08-06 17:32:11 [INFO]: 127.0.0.1 - - [06/Aug/2023 17:32:11] "[35m[1mGET /get_by_id/25 HTTP/1.1[0m" 500 -
2023-08-06 17:32:16 [INFO]: 127.0.0.1 - - [06/Aug/2023 17:32:16] "[33mGET /get_by_id HTTP/1.1[0m" 404 -
2023-08-06 17:32:35 [INFO]: 127.0.0.1 - - [06/Aug/2023 17:32:35] "[33mGET /get_by_id HTTP/1.1[0m" 404 -
2023-08-06 17:32:40 [ERROR]: Exception on /get_by_id/25 [GET]
Traceback (most recent call last):
  File "C:\Users\Vikas Datir\PycharmProjects\py_restapi\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Vikas Datir\PycharmProjects\py_restapi\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Vikas Datir\PycharmProjects\py_restapi\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Vikas Datir\PycharmProjects\py_restapi\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Vikas Datir\PycharmProjects\py_restapi\rest_api_app.py", line 53, in get_by_id
    cust_obj = Customers(config)
NameError: name 'config' is not defined
2023-08-06 17:32:40 [INFO]: 127.0.0.1 - - [06/Aug/2023 17:32:40] "[35m[1mGET /get_by_id/25 HTTP/1.1[0m" 500 -
